2024-09-28 15:38:14,306 | INFO | START BOT
2024-09-28 15:38:14,541 | INFO | Bot: IMGAi [@imagesAI_bot]
2024-09-28 15:38:14,541 | INFO | Start polling.
2024-09-28 15:38:21,374 | WARNING | User 678552784 is register
2024-09-28 15:38:34,474 | WARNING | This file is already in the database: dog.png
2024-09-28 15:38:44,838 | WARNING | Invalid file name: vfvdf .png
2024-09-28 15:38:52,434 | INFO | START generation image
2024-09-28 15:38:52,532 | INFO | There are still requests left - 20
2024-09-28 15:39:02,604 | INFO | There are still requests left - 19
2024-09-28 15:39:12,704 | INFO | There are still requests left - 18
2024-09-28 15:39:22,769 | INFO | There are still requests left - 17
2024-09-28 15:39:32,852 | INFO | There are still requests left - 16
2024-09-28 15:39:32,995 | INFO | Successfully generate generic_photo_user/krolik.png
2024-09-28 15:39:40,175 | INFO | Image re-engineering 678552784
2024-09-28 15:39:40,394 | INFO | START generation image
2024-09-28 15:39:40,497 | INFO | There are still requests left - 20
2024-09-28 15:39:50,566 | INFO | There are still requests left - 19
2024-09-28 15:40:00,692 | INFO | There are still requests left - 18
2024-09-28 15:40:10,795 | INFO | There are still requests left - 17
2024-09-28 15:40:20,932 | INFO | There are still requests left - 16
2024-09-28 15:40:21,083 | INFO | Successfully generate generic_photo_user/krolik.png
2024-09-28 15:40:26,124 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-41' coro=<Dispatcher._process_polling_updates() done, defined at D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:410> exception=InvalidQueryID('Query is too old and response timeout expired or query id is invalid')>
Traceback (most recent call last):
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 284, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "D:\Рабочий стол\Urban University\DIPLOM_project\IMGi_bot\reg_func.py", line 113, in repeat_image
    await call.answer()
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\types\callback_query.py", line 57, in answer
    return await self.bot.answer_callback_query(callback_query_id=self.id,
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\bot\bot.py", line 2890, in answer_callback_query
    return await self.request(api.Methods.ANSWER_CALLBACK_QUERY, payload)
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.InvalidQueryID: Query is too old and response timeout expired or query id is invalid
2024-09-28 15:40:26,143 | INFO | The image krolik.png was saved successfully
2024-09-28 15:40:47,270 | INFO | Stop polling...
2024-09-28 15:40:47,271 | WARNING | Goodbye!
